# Site settings
title: clarkieRyan.
description: "Javascript developer currently working for <a href='https://twitter.com/betssongroup'>@betssongroup</a>"
url: 'http://clarkieryan.com'
baseurl: '/jekyll-uno/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Ryan Clarke'
  email: clarkie.ryan@gmail.com
  twitter_username: clarkieryan
#  facebook_username: clarkieryan
  github_username:  clarkieryan
  linkedin_username:  clarkieryan

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
